name: Build CF_mipsle_mips,Alist_mipsle
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      ver: ${{ steps.getversion.outputs.ver }}
      cver: ${{ steps.getversion.outputs.cver }}
    steps:
      -
        name: Get version
        id: getversion
        run: |
          sudo timedatectl set-timezone "Asia/Shanghai"
          ver=`curl https://api.github.com/repos/cloudflare/cloudflared/releases/latest | jq -r '.tag_name'`
          cver=`curl https://api.github.com/repos/dearxjoe/cloudflared_mipsle_mips/releases/latest | jq -r '.tag_name'`
          echo "ver=${ver}" >> $GITHUB_OUTPUT
          echo "cver=${cver}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.ver != needs.check.outputs.cver }}
    steps:
      - 
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.3
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Build
        run: |
          git clone https://github.com/cloudflare/cloudflared -b ${{ needs.check.outputs.ver }} ../src
          git clone https://github.com/dearxjoe/cloudflared_mipsle_mips.git /opt/st
          cd ../src
          tar -xvf /opt/st/upx-3.95-amd64_linux.tar.xz -C /opt
          chmod 777 /opt/upx-3.95-amd64_linux/upx
          chmod 777 /opt/st/strip

          # Build for mipsle
          GOOS=linux GOARCH=mipsle GOMIPS=softfloat make cloudflared
          mv cloudflared cloudflared-linux-mipsle
          /opt/st/strip cloudflared-linux-mipsle
          /opt/upx-3.95-amd64_linux/upx --lzma --best cloudflared-linux-mipsle
          echo $(md5sum cloudflared-linux-mipsle | awk '{print $1;}') >MD5_cloudflared-linux-mipsle.txt

          # Build for mips
          GOOS=linux GOARCH=mips GOMIPS=softfloat make cloudflared
          mv cloudflared cloudflared-linux-mips    
          /opt/st/strip cloudflared-linux-mips
          /opt/upx-3.95-amd64_linux/upx --lzma --best cloudflared-linux-mips
          echo $(md5sum cloudflared-linux-mips | awk '{print $1;}') >MD5_cloudflared-linux-mips.txt

          # dowload Alist V3.38.0 alist-linux-musl-mipsle.tar.gz
          wget https://github.com/AlistGo/alist/releases/download/v3.38.0/alist-linux-musl-mipsle.tar.gz
          tar -xvf alist-linux-musl-mipsle.tar.gz
          mv alist alist_mipsle
          /opt/st/strip alist_mipsle
          /opt/upx-3.95-amd64_linux/upx --lzma --best alist_mipsle
          echo $(md5sum alist_mipsle | awk '{print $1;}') >MD5_alist_mipsle.txt
          
          echo "build_time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
          
          
      - 
        name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.check.outputs.ver }}
          body: |
           > ### 编译时间 ：${{ env.build_time }}

           本项目编译出的cloudflared二进制文件已经过lzma压缩，比原官方编译出的文件体积小很多，适合路由器等低内存的linux环境运行。如老毛子padavan固件。
           另外添加了alist v3.38.0版的mipsle架构的二进制文件，同样已压缩，比官方文件小，方便玩家使用。
           
           **[cloudflared官方更新说明](https://github.com/cloudflare/cloudflared/releases)**
           **[Alist官方更新说明](https://github.com/alist-org/alist/releases)**
           
          files: |
              ../src/cloudflared-linux-mipsle
              ../src/MD5_cloudflared-linux-mipsle.txt
              ../src/cloudflared-linux-mips
              ../src/MD5_cloudflared-linux-mips.txt
              ../src/alist_mipsle
              ../src/MD5_alist_mipsle.txt
